apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-fast-api
  labels:
    app: my-fast-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # Ajuste conforme sua configuração
  rules:
    - host: chart-example.local # Substitua por um nome de domínio ou IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-fast-api
                port:
                  number: 80
