name: Docker Build, Push and Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-fastapi-app .

    - name: List Docker images
      run: docker images

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-fastapi-app
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: |
          $(docker save my-fastapi-app | tee /tmp/my-fastapi-app.tar | cat)
      
  build-and-push:
    runs-on: ubuntu-latest
    needs: trivy-scan
    if: success()
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Load Docker image
      run: docker load -i my-fastapi-app.tar

    - name: List Docker images after load
      run: docker images

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: |
        docker tag my-fastapi-app:latest ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
