name: Trivy Scan and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-fastapi-app .

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-fastapi-app
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true

    - name: Tag Docker image
      run: |
        docker tag my-fastapi-app:latest ${DOCKER_USERNAME}/my-fastapi-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${DOCKER_USERNAME}/my-fastapi-app:latest
